return {
  { "bufferline.nvim", enabled = false },
  { "dashboard-nvim", enabled = false },
  { "flash.nvim", enabled = false },
  { "mini.ai", enabled = false },
  { "mini.pairs", enabled = false },
  { "neo-tree.nvim", enabled = false },
  { "noice.nvim", enabled = false },
  { "nui.nvim", enabled = false },
  { "nvim-notify", enabled = false },
  { "nvim-web-devicons", enabled = false },
  { "which-key.nvim", enabled = false },
  { "catppuccin", enabled = false },
  { "dressing.nvim", enabled = false },
  { "friendly-snippets", enabled = false },
  { "indent-blankline.nvim", enabled = false },
  { "mini.bufremove", enabled = false },
  { "mini.indentscope", enabled = false },
  { "mini.surround", enabled = false },
  { "neoconf.nvim", enabled = false },
  { "neodev.nvim", enabled = false },
  { "nvim-spectre", enabled = false },
  { "nvim-treesitter-context", enabled = false },
  { "persistence.nvim", enabled = false },
  { "tokyonight.nvim ", enabled = false },
  { "trouble.nvim", enabled = false },
  { "vim-illuminate", enabled = false },
  { "vim-startuptime", enabled = false },
  { "fzf-lua", enabled = false },
  { "blink.cmp", enabled = false },
  {
    "snacks.nvim",
    opts = {
      animate = { enabled = false },
      bigfile = { enabled = false },
      bufdelete = { enabled = false },
      dashboard = { enabled = false },
      debug = { enabled = false },
      dim = { enabled = false },
      explorer = { enabled = false },
      git = { enabled = false },
      gitbrowse = { enabled = false },
      image = { enabled = false },
      indent = { enabled = false },
      input = { enabled = false },
      layout = { enabled = false },
      lazygit = { enabled = false },
      notifier = { enabled = false },
      notify = { enabled = false },
      picker = { enabled = false },
      quickfile = { enabled = false },
      rename = { enabled = false },
      scope = { enabled = false },
      scratch = { enabled = false },
      scroll = { enabled = false },
      statuscolumn = { enabled = false },
      terminal = { enabled = false },
      toggle = { enabled = false },
      util = { enabled = false },
      win = { enabled = false },
      words = { enabled = false },
      zen = { enabled = false },
    },
    keys = {},
    init = function() end,
  },
}
